from colors import BaseColors


def get_ui_colors() -> dict:
    basecolors = BaseColors()
    
    return {
        #	https://code.visualstudio.com/api/references/theme-color
        
        #	<<- Base colors ->>
        "focusBorder": basecolors.bg0,
        "foreground": basecolors.fg0,
        # "disabledForeground": basecolors.red,
        "widget.border": basecolors.bg1,
        "widget.shadow": basecolors.bg0 + "10",
        # "selection.background": basecolors.red,
        # "descriptionForeground": basecolors.red,
        # "errorForeground": basecolors.red,
        # "icon.foreground": basecolors.red,
        "sash.hoverBorder": basecolors.bg1,
        
        #	<<- Window border ->>
        # "window.activeBorder": basecolors.red,
        # "window.inactiveBorder": basecolors.red,

        #	<<- Text colors ->>
        # "textBlockQuote.background": basecolors.red,
        # "textBlockQuote.border": basecolors.red,
        # "textCodeBlock.background": basecolors.red,
        # "textLink.activeForeground": basecolors.red,
        # "textLink.foreground": basecolors.red,
        # "textPreformat.foreground": basecolors.red,
        # "textSeparator.foreground": basecolors.red,

        #	<<- Action colors ->>
        "toolbar.hoverBackground": basecolors.bg1,
        "toolbar.hoverOutline": basecolors.bg1,
        "toolbar.activeBackground": basecolors.bg0,

        #	<<- Button control ->>
        # "button.background": basecolors.red,
        # "button.foreground": basecolors.red,
        # "button.border": basecolors.red,
        # "button.separator": basecolors.red,
        # "button.hoverBackground": basecolors.red,
        # "button.secondaryForeground": basecolors.red,
        # "button.secondaryBackground": basecolors.red,
        # "button.secondaryHoverBackground": basecolors.red,
        # "checkbox.background": basecolors.red,
        # "checkbox.foreground": basecolors.red,
        # "checkbox.border": basecolors.red,
        # "checkbox.selectBackground": basecolors.red,
        # "checkbox.selectBorder": basecolors.red,

        #  <<- Dropdown control ->>
        "dropdown.background": basecolors.bg1,
        "dropdown.listBackground": basecolors.bg1,
        "dropdown.border": basecolors.bg0,
        "dropdown.foreground": basecolors.fg0,

        #  <<- Input control ->>
        "input.background": basecolors.bg1,
        "input.border": basecolors.bg1,
        "input.foreground": basecolors.fg0,
        # "input.placeholderForeground": basecolors.fg0,
        # "inputOption.activeBackground": basecolors.red,
        # "inputOption.activeBorder": basecolors.red,
        # "inputOption.activeForeground": basecolors.red,
        # "inputOption.hoverBackground": basecolors.red,
        # "inputValidation.errorBackground": basecolors.red,
        # "inputValidation.errorForeground": basecolors.red,
        # "inputValidation.errorBorder": basecolors.red,
        # "inputValidation.infoBackground": basecolors.red,
        # "inputValidation.infoForeground": basecolors.red,
        # "inputValidation.infoBorder": basecolors.red,
        # "inputValidation.warningBackground": basecolors.red,
        # "inputValidation.warningForeground": basecolors.red,
        # "inputValidation.warningBorder": basecolors.red,

        #  <<- Scrollbar control ->>
        # "scrollbar.shadow": basecolors.red,
        "scrollbarSlider.activeBackground": basecolors.bg1,
        "scrollbarSlider.background": basecolors.bg1,
        "scrollbarSlider.hoverBackground": basecolors.bg1,

        #  <<- Badge ->>
        # "badge.foreground": basecolors.red,
        # "badge.background": basecolors.red,

        #  <<- Progress bar ->>
        "progressBar.background": basecolors.accent0,

        #  <<- Lists and trees ->>
        "list.activeSelectionBackground": basecolors.bg2,
        "list.activeSelectionForeground": basecolors.fg0,
        "list.activeSelectionIconForeground": basecolors.fg0,
        # "list.dropBackground": basecolors.red,
        "list.focusBackground": basecolors.bg1,
        # "list.focusForeground": basecolors.red,
        # "list.focusHighlightForeground": basecolors.red,
        # "list.focusOutline": basecolors.red,
        # "list.focusAndSelectionOutline": basecolors.red,
        "list.highlightForeground": basecolors.red,
        "list.hoverBackground": basecolors.bg1,
        # "list.hoverForeground": basecolors.red,
        "list.inactiveSelectionBackground": basecolors.bg1,
        # "list.inactiveSelectionForeground": basecolors.red,
        # "list.inactiveSelectionIconForeground": basecolors.red,
        # "list.inactiveFocusBackground": basecolors.red,
        # "list.inactiveFocusOutline": basecolors.red,
        # "list.invalidItemForeground": basecolors.red,
        # "list.errorForeground": basecolors.red,
        # "list.warningForeground": basecolors.red,
        # "listFilterWidget.background": basecolors.red,
        # "listFilterWidget.outline": basecolors.red,
        # "listFilterWidget.noMatchesOutline": basecolors.red,
        # "listFilterWidget.shadow": basecolors.red,
        # "list.filterMatchBackground": basecolors.red,
        # "list.filterMatchBorder": basecolors.red,
        # "list.deemphasizedForeground": basecolors.red,
        # "tree.indentGuidesStroke": basecolors.red,
        # "tree.inactiveIndentGuidesStroke": basecolors.red,
        # "tree.tableColumnsBorder": basecolors.red,
        # "tree.tableOddRowsBackground": basecolors.red,

        #  <<- Activity Bar ->>
        "activityBar.background": basecolors.bg0,
        # "activityBar.dropBorder": basecolors.accent0,
        "activityBar.foreground": basecolors.fg0,
        "activityBar.inactiveForeground": basecolors.fg2,
        "activityBar.border": basecolors.bg1,
        "activityBarBadge.background": basecolors.accent0,
        "activityBarBadge.foreground": basecolors.bg0,
        "activityBar.activeBorder": basecolors.accent0,
        "activityBar.activeBackground": basecolors.bg0,
        "activityBar.activeFocusBorder": basecolors.accent0,

        #  <<- Side Bar ->>
        "sideBar.background": basecolors.bg0,
        "sideBar.foreground": basecolors.fg1,
        "sideBar.border": basecolors.bg1,
        # "sideBar.dropBackground": basecolors.red,
        "sideBarTitle.foreground": basecolors.fg0,
        "sideBarSectionHeader.background": basecolors.bg0,
        "sideBarSectionHeader.foreground": basecolors.fg0,
        "sideBarSectionHeader.border": basecolors.bg1,

        #  <<- Minimap ->>
        # "minimap.findMatchHighlight": basecolors.red,
        # "minimap.selectionHighlight": basecolors.red,
        # "minimap.errorHighlight": basecolors.red,
        # "minimap.warningHighlight": basecolors.red,
        # "minimap.background": basecolors.red,
        # "minimap.selectionOccurrenceHighlight": basecolors.red,
        # "minimap.foregroundOpacity": basecolors.red,
        # "minimapSlider.background": basecolors.red,
        # "minimapSlider.hoverBackground": basecolors.red,
        # "minimapSlider.activeBackground": basecolors.red,
        # "minimapGutter.addedBackground": basecolors.red,
        # "minimapGutter.modifiedBackground": basecolors.red,
        # "minimapGutter.deletedBackground": basecolors.red,

        #  <<- Editor Groups & Tabs ->>
        "editorGroup.border": basecolors.bg1,
        # "editorGroup.dropBackground": basecolors.accent0,
        "editorGroupHeader.noTabsBackground": basecolors.bg0,
        "editorGroupHeader.tabsBackground": basecolors.bg0,
        "editorGroupHeader.tabsBorder": basecolors.bg1,
        "editorGroupHeader.border": basecolors.bg0,
        "editorGroup.emptyBackground": basecolors.bg1,
        # "editorGroup.focusedEmptyBorder": basecolors.bg0,
        # "editorGroup.dropIntoPromptForeground": basecolors.red,
        # "editorGroup.dropIntoPromptBackground": basecolors.red,
        # "editorGroup.dropIntoPromptBorder": basecolors.red,
        "tab.activeBackground": basecolors.bg0,
        "tab.unfocusedActiveBackground": basecolors.bg0,
        "tab.activeForeground": basecolors.fg0,
        "tab.unfocusedActiveForeground": basecolors.fg0,
        "tab.border": basecolors.bg1,
        "tab.activeBorder": basecolors.bg0,
        "tab.unfocusedActiveBorder": basecolors.bg0,
        "tab.activeBorderTop": basecolors.accent0,
        "tab.unfocusedActiveBorderTop": basecolors.accent0,
        # "tab.lastPinnedBorder": basecolors.red,
        "tab.inactiveBackground": basecolors.bg0,
        "tab.unfocusedInactiveBackground": basecolors.bg0,
        "tab.inactiveForeground": basecolors.fg1,
        "tab.unfocusedInactiveForeground": basecolors.fg1,
        "tab.hoverBackground": basecolors.bg0,
        "tab.unfocusedHoverBackground": basecolors.bg0,
        "tab.hoverForeground": basecolors.accent0,
        "tab.unfocusedHoverForeground": basecolors.accent0,
        # "tab.hoverBorder": basecolors.red,
        # "tab.unfocusedHoverBorder": basecolors.red,
        # "tab.activeModifiedBorder": basecolors.red,
        # "tab.inactiveModifiedBorder": basecolors.red,
        # "tab.unfocusedActiveModifiedBorder": basecolors.red,
        # "tab.unfocusedInactiveModifiedBorder": basecolors.red,
        # "editorPane.background": basecolors.red,
        # "sideBySideEditor.horizontalBorder": basecolors.red,
        # "sideBySideEditor.verticalBorder": basecolors.red,

        #  <<- Editor colors ->>
        "editor.background": basecolors.bg0,
        "editor.foreground": basecolors.fg0,
        "editorLineNumber.foreground": basecolors.fg2,
        "editorLineNumber.activeForeground": basecolors.fg1,
        # "editorLineNumber.dimmedForeground": basecolors.bg0,
        # "editorLineNumber.dimmedForeground": basecolors.bg0,
        "editorCursor.background": basecolors.accent0,
        "editorCursor.foreground": basecolors.accent0,
        "editor.selectionBackground": basecolors.accent1 + "30",
        # "editor.selectionForeground": basecolors.red,
        "editor.inactiveSelectionBackground": basecolors.accent1 + "50",
        # "editor.selectionHighlightBackground": basecolors.red,
        "editor.selectionHighlightBorder": basecolors.accent0,
        "editor.wordHighlightBackground": basecolors.bg2,
        # "editor.wordHighlightBorder": basecolors.red,
        # "editor.wordHighlightStrongBackground": basecolors.red,
        # "editor.wordHighlightStrongBorder": basecolors.red,
        # "editor.wordHighlightTextBackground": basecolors.red,
        # "editor.wordHighlightTextBorder": basecolors.red,
        # "editor.findMatchBackground": basecolors.red,
        # "editor.findMatchHighlightBackground": basecolors.red,
        # "editor.findRangeHighlightBackground": basecolors.red,
        # "editor.findMatchBorder": basecolors.red,
        # "editor.findMatchHighlightBorder": basecolors.red,
        # "editor.findRangeHighlightBorder": basecolors.red,
        # "searchEditor.findMatchBackground": basecolors.red,
        # "searchEditor.findMatchBorder": basecolors.red,
        # "searchEditor.textInputBorder": basecolors.red,
        "editor.hoverHighlightBackground": basecolors.accent1 + "30",
        "editor.lineHighlightBackground": basecolors.bg1 + "00",
        "editor.lineHighlightBorder": basecolors.bg0,
        # "editorUnicodeHighlight.border": basecolors.red,
        # "editorUnicodeHighlight.background": basecolors.red,
        # "editorLink.activeForeground": basecolors.red,
        # "editor.rangeHighlightBackground": basecolors.red,
        # "editor.rangeHighlightBorder": basecolors.red,
        # "editor.symbolHighlightBackground": basecolors.red,
        # "editor.symbolHighlightBorder": basecolors.red,
        "editorWhitespace.foreground": basecolors.bg2,
        "editorIndentGuide.background": basecolors.bg1,
        "editorIndentGuide.activeBackground": basecolors.bg1,
        # "editorInlayHint.background": basecolors.bg1,
        # "editorInlayHint.foreground": basecolors.bg1,
        # "editorInlayHint.typeForeground": basecolors.bg1,
        # "editorInlayHint.typeBackground": basecolors.bg1,
        # "editorInlayHint.parameterForeground": basecolors.bg1,
        # "editorInlayHint.parameterBackground": basecolors.bg1,
        "editorRuler.foreground": basecolors.bg1,
        # "editor.linkedEditingBackground": basecolors.bg1,
        # "editorCodeLens.foreground": basecolors.red,
        # "editorLightBulb.foreground": basecolors.red,
        # "editorLightBulbAutoFix.foreground": basecolors.red,
        # "editorBracketMatch.foreground": basecolors.red,
        # "editorBracketMatch.border": basecolors.red,
        "editorBracketHighlight.foreground1": basecolors.fg0 + "90",
        "editorBracketHighlight.foreground2": basecolors.fg0 + "90",
        "editorBracketHighlight.foreground3": basecolors.fg0 + "90",
        "editorBracketHighlight.foreground4": basecolors.fg0 + "90",
        "editorBracketHighlight.foreground5": basecolors.fg0 + "90",
        "editorBracketHighlight.foreground6": basecolors.fg0 + "90",
        # "editorBracketHighlight.unexpectedBracket.foreground": basecolors.red,
        # "editorBracketPairGuide.activeBackground1": basecolors.red,
        # "editorBracketPairGuide.activeBackground2": basecolors.red,
        # "editorBracketPairGuide.activeBackground3": basecolors.red,
        # "editorBracketPairGuide.activeBackground4": basecolors.red,
        # "editorBracketPairGuide.activeBackground5": basecolors.red,
        # "editorBracketPairGuide.activeBackground6": basecolors.red,
        # "editorBracketPairGuide.background1": basecolors.red,
        # "editorBracketPairGuide.background2": basecolors.red,
        # "editorBracketPairGuide.background3": basecolors.red,
        # "editorBracketPairGuide.background4": basecolors.red,
        # "editorBracketPairGuide.background5": basecolors.red,
        # "editorBracketPairGuide.background6": basecolors.red,
        # "editor.foldBackground": basecolors.red,
        # "editorOverviewRuler.background": basecolors.red,
        # "editorOverviewRuler.border": basecolors.red,
        # "editorOverviewRuler.findMatchForeground": basecolors.red,
        # "editorOverviewRuler.rangeHighlightForeground": basecolors.red,
        # "editorOverviewRuler.selectionHighlightForeground": basecolors.red,
        # "editorOverviewRuler.wordHighlightForeground": basecolors.red,
        # "editorOverviewRuler.wordHighlightStrongForeground": basecolors.red,
        # "editorOverviewRuler.wordHighlightTextForeground": basecolors.red,
        # "editorOverviewRuler.modifiedForeground": basecolors.red,
        # "editorOverviewRuler.addedForeground": basecolors.red,
        # "editorOverviewRuler.deletedForeground": basecolors.red,
        # "editorOverviewRuler.errorForeground": basecolors.red,
        # "editorOverviewRuler.warningForeground": basecolors.red,
        # "editorOverviewRuler.infoForeground": basecolors.red,
        # "editorOverviewRuler.bracketMatchForeground": basecolors.red,
        # "editorError.foreground": basecolors.red,
        # "editorError.border": basecolors.red,
        # "editorError.background": basecolors.red,
        # "editorWarning.foreground": basecolors.red,
        # "editorWarning.border": basecolors.red,
        # "editorWarning.background": basecolors.red,
        # "editorInfo.foreground": basecolors.red,
        # "editorInfo.border": basecolors.red,
        # "editorInfo.background": basecolors.red,
        # "editorHint.foreground": basecolors.red,
        # "editorHint.border": basecolors.red,
        # "problemsErrorIcon.foreground": basecolors.red,
        # "problemsWarningIcon.foreground": basecolors.red,
        # "problemsInfoIcon.foreground": basecolors.red,
        # "editorUnnecessaryCode.border": basecolors.red,
        # "editorUnnecessaryCode.opacity": basecolors.red,
        # "editorUnnecessaryCode.opacity": basecolors.red,
        # "editorGutter.modifiedBackground": basecolors.red,
        # "editorGutter.addedBackground": basecolors.red,
        # "editorGutter.deletedBackground": basecolors.red,
        # "editorGutter.commentRangeForeground": basecolors.red,
        # "editorGutter.commentGlyphForground": basecolors.red,
        # "editorGutter.foldingControlForeground": basecolors.red,
        # "editorCommentsWidget.resolvedBorder": basecolors.red,
        # "editorCommentsWidget.unresolvedBorder": basecolors.red,
        # "editorCommentsWidget.rangeBackground": basecolors.red,
        # "editorCommentsWidget.rangeBorder": basecolors.red,
        # "editorCommentsWidget.rangeActiveBackground": basecolors.red,
        # "editorCommentsWidget.rangeActiveBorder": basecolors.red,

        #  <<- Diff editor colors ->>
        # "diffEditor.insertedTextBackground": basecolors.red,
        # "diffEditor.insertedTextBorder": basecolors.red,
        # "diffEditor.removedTextBackground": basecolors.red,
        # "diffEditor.removedTextBorder": basecolors.red,
        # "diffEditor.border": basecolors.red,
        # "diffEditor.diagonalFill": basecolors.red,
        # "diffEditor.insertedLineBackground": basecolors.red,
        # "diffEditor.removedLineBackground": basecolors.red,
        # "diffEditorGutter.insertedLineBackground": basecolors.red,
        # "diffEditorGutter.removedLineBackground": basecolors.red,
        # "diffEditorOverview.insertedForeground": basecolors.red,
        # "diffEditorOverview.removedForeground": basecolors.red,

        #  <<- Editor widget colors ->>
        # "editorWidget.foreground": basecolors.red,
        # "editorWidget.background": basecolors.red,
        # "editorWidget.border": basecolors.red,
        # "editorWidget.resizeBorder": basecolors.red,
        # "editorSuggestWidget.background": basecolors.red,
        # "editorSuggestWidget.border": basecolors.red,
        # "editorSuggestWidget.foreground": basecolors.red,
        # "editorSuggestWidget.focusHighlightForeground": basecolors.red,
        # "editorSuggestWidget.highlightForeground": basecolors.red,
        # "editorSuggestWidget.selectedBackground": basecolors.red,
        # "editorSuggestWidget.selectedForeground": basecolors.red,
        # "editorSuggestWidget.selectedIconForeground": basecolors.red,
        # "editorSuggestWidgetStatus.foreground": basecolors.red,
        # "editorHoverWidget.foreground": basecolors.red,
        # "editorHoverWidget.background": basecolors.red,
        # "editorHoverWidget.border": basecolors.red,
        # "editorHoverWidget.highlightForeground": basecolors.red,
        # "editorHoverWidget.statusBarBackground": basecolors.red,
        # "editorGhostText.border": basecolors.red,
        # "editorGhostText.background": basecolors.red,
        # "editorGhostText.foreground": basecolors.red,
        # "editorStickyScroll.background": basecolors.red,
        # "editorStickyScrollHover.background": basecolors.red,
        # "debugExceptionWidget.background": basecolors.red,
        # "debugExceptionWidget.border": basecolors.red,
        # "editorMarkerNavigation.background": basecolors.red,
        # "editorMarkerNavigationError.background": basecolors.red,
        # "editorMarkerNavigationWarning.background": basecolors.red,
        # "editorMarkerNavigationInfo.background": basecolors.red,
        # "editorMarkerNavigationError.headerBackground": basecolors.red,
        # "editorMarkerNavigationWarning.headerBackground": basecolors.red,
        # "editorMarkerNavigationInfo.headerBackground": basecolors.red,

        #  <<- Peek view colors ->>
        # "peekView.border": basecolors.red,
        # "peekViewEditor.background": basecolors.red,
        # "peekViewEditorGutter.background": basecolors.red,
        # "peekViewEditor.matchHighlightBackground": basecolors.red,
        # "peekViewEditor.matchHighlightBorder": basecolors.red,
        # "peekViewEditorStickScroll.background": basecolors.red,
        # "peekViewResult.background": basecolors.red,
        # "peekViewResult.fileForeground": basecolors.red,
        # "peekViewResult.lineForeground": basecolors.red,
        # "peekViewResult.matchHighlightBackground": basecolors.red,
        # "peekViewResult.selectionBackground": basecolors.red,
        # "peekViewResult.selectionForeground": basecolors.red,
        # "peekViewTitle.background": basecolors.red,
        # "peekViewTitleDescription.foreground": basecolors.red,
        # "peekViewTitleLabel.foreground": basecolors.red,

        #  <<- Merge conflicts colors ->>
        # "merge.currentHeaderBackground": basecolors.red,
        # "merge.currentContentBackground": basecolors.red,
        # "merge.incomingHeaderBackground": basecolors.red,
        # "merge.incomingContentBackground": basecolors.red,
        # "merge.border": basecolors.red,
        # "merge.commonContentBackground": basecolors.red,
        # "merge.commonHeaderBackground": basecolors.red,
        # "editorOverviewRuler.currentContentForeground": basecolors.red,
        # "editorOverviewRuler.incomingContentForeground": basecolors.red,
        # "editorOverviewRuler.commonContentForeground": basecolors.red,
        # "mergeEditor.change.background": basecolors.red,
        # "mergeEditor.change.word.background": basecolors.red,
        # "mergeEditor.conflict.unhandledUnfocused.border": basecolors.red,
        # "mergeEditor.conflict.unhandledFocused.border": basecolors.red,
        # "mergeEditor.conflict.handledUnfocused.border": basecolors.red,
        # "mergeEditor.conflict.handledFocused.border": basecolors.red,
        # "mergeEditor.conflict.handled.minimapOverViewRuler": basecolors.red,
        # "mergeEditor.conflict.unhandled.minimapOverViewRuler": basecolors.red,
        # "mergeEditor.conflictingLines.background": basecolors.red,
        # "mergeEditor.changeBase.background": basecolors.red,
        # "mergeEditor.changeBase.word.background": basecolors.red,
        # "mergeEditor.conflict.input1.background": basecolors.red,
        # "mergeEditor.conflict.input2.background": basecolors.red,

        #  <<- Panel colors ->>
        "panel.background": basecolors.bg0,
        "panel.border": basecolors.bg1,
        # "panel.dropBorder": basecolors.red,
        "panelTitle.activeBorder": basecolors.accent0,
        "panelTitle.activeForeground": basecolors.fg0,
        "panelTitle.inactiveForeground": basecolors.fg1,
        # "panelInput.border": basecolors.red,
        # "panelSection.border": basecolors.red,
        # "panelSection.dropBackground": basecolors.red,
        # "panelSectionHeader.background": basecolors.red,
        # "panelSectionHeader.foreground": basecolors.red,
        # "panelSectionHeader.border": basecolors.red,

        #  <<- Status Bar colors ->>
        "statusBar.background": basecolors.bg0,
        "statusBar.foreground": basecolors.fg1,
        "statusBar.border": basecolors.bg1,
        # "statusBar.debuggingBackground": basecolors.bg0,
        # "statusBar.debuggingForeground": basecolors.bg0,
        # "statusBar.debuggingBorder": basecolors.bg0,
        "statusBar.noFolderForeground": basecolors.fg0,
        # "statusBar.noFolderBackground": basecolors.accent0,
        # "statusBar.noFolderBorder": basecolors.bg0,
        # "statusBarItem.activeBackground": basecolors.bg0,
        # "statusBarItem.hoverBackground": basecolors.bg0,
        # "statusBarItem.prominentForeground": basecolors.bg0,
        # "statusBarItem.prominentBackground": basecolors.bg0,
        # "statusBarItem.prominentHoverBackground": basecolors.bg0,
        # "statusBarItem.remoteBackground": basecolors.accent0,
        # "statusBarItem.remoteForeground": basecolors.bg1,
        # "statusBarItem.errorBackground": basecolors.bg0,
        # "statusBarItem.errorForeground": basecolors.bg0,
        # "statusBarItem.warningBackground": basecolors.bg0,
        # "statusBarItem.warningForeground": basecolors.bg0,
        # "statusBarItem.compactHoverBackground": basecolors.bg0,
        # "statusBarItem.focusBorder": basecolors.bg0,
        # "statusBar.focusBorder": basecolors.bg0,

        #  <<- Title Bar colors ->>
        "titleBar.activeBackground": basecolors.bg0,
        "titleBar.activeForeground": basecolors.fg1,
        "titleBar.inactiveBackground": basecolors.bg0,
        "titleBar.inactiveForeground": basecolors.fg1,
        "titleBar.border": basecolors.bg1,

        #  <<- Menu Bar colors ->>
        "menubar.selectionForeground": basecolors.fg0,
        "menubar.selectionBackground": basecolors.bg0,
        "menubar.selectionBorder": basecolors.bg0,
        "menu.foreground": basecolors.fg1,
        "menu.background": basecolors.bg1,
        "menu.selectionForeground": basecolors.fg0,
        "menu.selectionBackground": basecolors.bg0,
        "menu.selectionBorder": basecolors.bg0,
        "menu.separatorBackground": basecolors.bg0,
        "menu.border": basecolors.bg0,

        #  <<- Command Center colors ->>
        "commandCenter.foreground": basecolors.fg1,
        "commandCenter.background": basecolors.bg1,
        "commandCenter.border": basecolors.bg0,
        "commandCenter.activeForeground": basecolors.fg1,
        "commandCenter.activeBackground": basecolors.bg0,
        "commandCenter.activeBorder": basecolors.bg1,
        "commandCenter.inactiveBorder": basecolors.bg0,
        "commandCenter.inactiveForeground": basecolors.fg1,

        #  <<- Notification colors ->>
        "notificationCenter.border": basecolors.bg1,
        "notificationCenterHeader.foreground": basecolors.fg1,
        "notificationCenterHeader.background": basecolors.bg1,
        "notificationToast.border": basecolors.bg1,
        "notifications.foreground": basecolors.fg1,
        "notifications.background": basecolors.bg1,
        "notifications.border": basecolors.bg1,
        # "notificationLink.foreground": basecolors.red,
        # "notificationsErrorIcon.foreground": basecolors.red,
        # "notificationsWarningIcon.foreground": basecolors.red,
        # "notificationsInfoIcon.foreground": basecolors.red,

        #  <<- Banner colors ->>
        # "banner.background": basecolors.red,
        # "banner.foreground": basecolors.red,
        # "banner.iconForeground": basecolors.red,

        #  <<- Extensions colors ->>
        # "extensionButton.prominentForeground": basecolors.red,
        # "extensionButton.prominentBackground": basecolors.red,
        # "extensionButton.prominentHoverBackground": basecolors.red,
        # "extensionButton.background": basecolors.red,
        # "extensionButton.foreground": basecolors.red,
        # "extensionButton.hoverBackground": basecolors.red,
        # "extensionButton.separator": basecolors.red,
        # "extensionBadge.remoteBackground": basecolors.red,
        # "extensionBadge.remoteForeground": basecolors.red,
        # "extensionIcon.starForeground": basecolors.red,
        # "extensionIcon.verifiedForeground": basecolors.red,
        # "extensionIcon.preReleaseForeground": basecolors.red,
        # "extensionIcon.sponsorForeground": basecolors.red,

        #  <<- Quick picker colors ->>
        "pickerGroup.border": basecolors.bg0,
        # "pickerGroup.foreground": basecolors.fg0,
        "quickInput.background": basecolors.bg1,
        "quickInput.foreground": basecolors.fg1,
        "quickInputList.focusBackground": basecolors.bg0,
        "quickInputList.focusForeground": basecolors.fg0,
        "quickInputList.focusIconForeground": basecolors.fg0,
        # "quickInputTitle.background": basecolors.red,

        #  <<- Keybinding label colors ->>
        "keybindingLabel.background": basecolors.bg0,
        "keybindingLabel.foreground": basecolors.fg1,
        "keybindingLabel.border": basecolors.bg1,
        "keybindingLabel.bottomBorder": basecolors.bg1,

        #  <<- Keyboard shortcut table colors ->>
        # "keybindingTable.headerBackground": basecolors.red,
        # "keybindingTable.rowsBackground": basecolors.red,

        #  <<- Integrated Terminal colors ->>
        "terminal.background": basecolors.bg0,
        "terminal.border": basecolors.bg1,
        "terminal.foreground": basecolors.fg0,
        "terminal.ansiBlack": basecolors.ansiBlack,
        "terminal.ansiBlue": basecolors.ansiBrightBlack,
        "terminal.ansiBrightBlack": basecolors.ansiBrightBlack,
        "terminal.ansiBrightBlue": basecolors.ansiBrightBlue,
        "terminal.ansiBrightCyan": basecolors.ansiBrightCyan,
        "terminal.ansiBrightGreen": basecolors.ansiBrightGreen,
        "terminal.ansiBrightMagenta": basecolors.ansiBrightMagenta,
        "terminal.ansiBrightRed": basecolors.ansiBrightRed,
        "terminal.ansiBrightWhite": basecolors.ansiBrightWhite,
        "terminal.ansiBrightYellow": basecolors.ansiBrightYellow,
        "terminal.ansiCyan": basecolors.ansiCyan,
        "terminal.ansiGreen": basecolors.ansiGreen,
        "terminal.ansiMagenta": basecolors.ansiMagenta,
        "terminal.ansiRed": basecolors.ansiRed,
        "terminal.ansiWhite": basecolors.ansiWhite,
        "terminal.ansiYellow": basecolors.ansiYellow,
        # "terminal.selectionBackground": basecolors.red,
        # "terminal.selectionForeground": basecolors.red,
        # "terminal.inactiveSelectionBackground": basecolors.red,
        # "terminal.findMatchBackground": basecolors.red,
        # "terminal.findMatchBorder": basecolors.red,
        # "terminal.findMatchHighlightBackground": basecolors.red,
        # "terminal.findMatchHighlightBorder": basecolors.red,
        "terminalCursor.background": basecolors.accent0,
        "terminalCursor.foreground": basecolors.accent0,
        # "terminal.dropBackground": basecolors.red,
        "terminal.tab.activeBorder": basecolors.accent0,
        # "terminalCommandDecoration.defaultBackground": basecolors.red,
        # "terminalCommandDecoration.successBackground": basecolors.red,
        # "terminalCommandDecoration.errorBackground": basecolors.red,
        # "terminalOverviewRuler.cursorForeground": basecolors.red,
        # "terminalOverviewRuler.findMatchForeground": basecolors.red,

        #  <<- Debug colors ->>
        # "debugToolBar.background": basecolors.red,
        # "debugToolBar.border": basecolors.red,
        # "editor.stackFrameHighlightBackground": basecolors.red,
        # "editor.focusedStackFrameHighlightBackground": basecolors.red,
        # "editor.inlineValuesForeground": basecolors.red,
        # "editor.inlineValuesBackground": basecolors.red,
        # "debugView.exceptionLabelForeground": basecolors.red,
        # "debugView.exceptionLabelBackground": basecolors.red,
        # "debugView.stateLabelForeground": basecolors.red,
        # "debugView.stateLabelBackground": basecolors.red,
        # "debugView.valueChangedHighlight": basecolors.red,
        # "debugTokenExpression.name": basecolors.red,
        # "debugTokenExpression.value": basecolors.red,
        # "debugTokenExpression.string": basecolors.red,
        # "debugTokenExpression.boolean": basecolors.red,
        # "debugTokenExpression.number": basecolors.red,
        # "debugTokenExpression.error": basecolors.red,

        #  <<- Testing colors ->>
        # "testing.iconFailed": basecolors.red,
        # "testing.iconErrored": basecolors.red,
        # "testing.iconPassed": basecolors.red,
        # "testing.runAction": basecolors.red,
        # "testing.iconQueued": basecolors.red,
        # "testing.iconUnset": basecolors.red,
        # "testing.iconSkipped": basecolors.red,
        # "testing.peekBorder": basecolors.red,
        # "testing.peekHeaderBackground": basecolors.red,
        # "testing.message.error.decorationForeground": basecolors.red,
        # "testing.message.error.lineBackground": basecolors.red,
        # "testing.message.info.decorationForeground": basecolors.red,
        # "testing.message.info.lineBackground": basecolors.red,

        #  <<- Welcome page colors ->>
        "welcomePage.background": basecolors.bg0,
        "welcomePage.progress.background": basecolors.bg2,
        # "welcomePage.progress.foreground": basecolors.bg1,
        "welcomePage.tileBackground": basecolors.bg1,
        "welcomePage.tileHoverBackground": basecolors.bg2,
        "welcomePage.tileBorder": basecolors.bg0,
        # "walkThrough.embeddedEditorBackground": basecolors.red,
        # "walkthrough.stepTitle.foreground": basecolors.red,
        # "welcomeOverlay.background": basecolors.red,

        #  <<- Source Control colors ->>
        # "scm.providerBorder": basecolors.red,

        #  <<- Git colors ->>
        # "gitDecoration.addedResourceForeground": basecolors.red,
        # "gitDecoration.modifiedResourceForeground": basecolors.red,
        # "gitDecoration.deletedResourceForeground": basecolors.red,
        # "gitDecoration.renamedResourceForeground": basecolors.red,
        # "gitDecoration.stageModifiedResourceForeground": basecolors.red,
        # "gitDecoration.stageDeletedResourceForeground": basecolors.red,
        # "gitDecoration.untrackedResourceForeground": basecolors.red,
        # "gitDecoration.ignoredResourceForeground": basecolors.red,
        # "gitDecoration.conflictingResourceForeground": basecolors.red,
        # "gitDecoration.submoduleResourceForeground": basecolors.red,

        #  <<- Settings Editor colors ->>
        # "settings.headerForeground": basecolors.accent0,
        "settings.modifiedItemIndicator": basecolors.accent0,
        "settings.dropdownBackground": basecolors.bg1,
        "settings.dropdownForeground": basecolors.fg1,
        "settings.dropdownBorder": basecolors.bg0,
        "settings.dropdownListBorder": basecolors.bg0,
        "settings.checkboxBackground": basecolors.bg2,
        "settings.checkboxForeground": basecolors.fg0,
        "settings.checkboxBorder": basecolors.bg1,
        "settings.rowHoverBackground": basecolors.bg1,
        "settings.textInputBackground": basecolors.bg1,
        "settings.textInputForeground": basecolors.fg1,
        "settings.textInputBorder": basecolors.bg0,
        "settings.numberInputBackground": basecolors.bg1,
        "settings.numberInputForeground": basecolors.fg1,
        "settings.numberInputBorder": basecolors.bg0,
        # "settings.focusedRowBackground": basecolors.red,
        # "settings.focusedRowBorder": basecolors.red,
        "settings.headerBorder": basecolors.bg1,
        "settings.sashBorder": basecolors.bg1,
        # "settings.settingsHeaderHoverForeground": basecolors.red,

        #  <<- Breadcrumbs colors ->>
        "breadcrumb.foreground": basecolors.fg1,
        "breadcrumb.background": basecolors.bg0,
        "breadcrumb.focusForeground": basecolors.fg0,
        "breadcrumb.activeSelectionForeground": basecolors.accent0,
        "breadcrumbPicker.background": basecolors.bg1,

        #  <<- Snippets colors ->>
        # "editor.snippetTabstopHighlightBackground": basecolors.red,
        # "editor.snippetTabstopHighlightBorder": basecolors.red,
        # "editor.snippetFinalTabstopHighlightBackground": basecolors.red,
        # "editor.snippetFinalTabstopHighlightBorder": basecolors.red,

        #  <<- Symbol Icon colors ->>
        # "symbolIcon.arrayForeground": basecolors.red,
        # "symbolIcon.booleanForeground": basecolors.red,
        # "symbolIcon.classForeground": basecolors.red,
        # "symbolIcon.colorForeground": basecolors.red,
        # "symbolIcon.constantForeground": basecolors.red,
        # "symbolIcon.constructorForeground": basecolors.red,
        # "symbolIcon.enumeratorForeground": basecolors.red,
        # "symbolIcon.enumeratorMemberForeground": basecolors.red,
        # "symbolIcon.eventForeground": basecolors.red,
        # "symbolIcon.fieldForeground": basecolors.red,
        # "symbolIcon.fileForeground": basecolors.red,
        # "symbolIcon.folderForeground": basecolors.red,
        # "symbolIcon.functionForeground": basecolors.red,
        # "symbolIcon.interfaceForeground": basecolors.red,
        # "symbolIcon.keyForeground": basecolors.red,
        # "symbolIcon.keywordForeground": basecolors.red,
        # "symbolIcon.methodForeground": basecolors.red,
        # "symbolIcon.moduleForeground": basecolors.red,
        # "symbolIcon.namespaceForeground": basecolors.red,
        # "symbolIcon.nullForeground": basecolors.red,
        # "symbolIcon.numberForeground": basecolors.red,
        # "symbolIcon.objectForeground": basecolors.red,
        # "symbolIcon.operatorForeground": basecolors.red,
        # "symbolIcon.packageForeground": basecolors.red,
        # "symbolIcon.propertyForeground": basecolors.red,
        # "symbolIcon.referenceForeground": basecolors.red,
        # "symbolIcon.snippetForeground": basecolors.red,
        # "symbolIcon.stringForeground": basecolors.red,
        # "symbolIcon.structForeground": basecolors.red,
        # "symbolIcon.textForeground": basecolors.red,
        # "symbolIcon.typeParameterForeground": basecolors.red,
        # "symbolIcon.unitForeground": basecolors.red,
        # "symbolIcon.variableForeground": basecolors.red,

        #  <<- Debug Icons colors ->>
        # "debugIcon.breakpointForeground": basecolors.red,
        # "debugIcon.breakpointDisabledForeground": basecolors.red,
        # "debugIcon.breakpointUnverifiedForeground": basecolors.red,
        # "debugIcon.breakpointCurrentStackframeForeground": basecolors.red,
        # "debugIcon.breakpointStackframeForeground": basecolors.red,
        # "debugIcon.startForeground": basecolors.red,
        # "debugIcon.pauseForeground": basecolors.red,
        # "debugIcon.stopForeground": basecolors.red,
        # "debugIcon.disconnectForeground": basecolors.red,
        # "debugIcon.restartForeground": basecolors.red,
        # "debugIcon.stepOverForeground": basecolors.red,
        # "debugIcon.stepIntoForeground": basecolors.red,
        # "debugIcon.stepOutForeground": basecolors.red,
        # "debugIcon.continueForeground": basecolors.red,
        # "debugIcon.stepBackForeground": basecolors.red,
        # "debugConsole.infoForeground": basecolors.red,
        # "debugConsole.warningForeground": basecolors.red,
        # "debugConsole.errorForeground": basecolors.red,
        # "debugConsole.sourceForeground": basecolors.red,
        # "debugConsoleInputIcon.foreground": basecolors.red,

        #  <<- Notebook colors ->>
        "notebook.editorBackground": basecolors.bg0,
        "notebook.cellBorderColor": basecolors.bg1,
        "notebook.cellHoverBackground": basecolors.bg0,
        # "notebook.cellInsertionIndicator": basecolors.red,
        # "notebook.cellStatusBarItemHoverBackground": basecolors.red,
        # "notebook.cellToolbarSeparator": basecolors.red,
        # "notebook.cellEditorBackground": basecolors.red,
        "notebook.focusedCellBackground": basecolors.bg0,
        "notebook.focusedCellBorder": basecolors.accent0,
        "notebook.focusedEditorBorder": basecolors.bg2,
        "notebook.inactiveFocusedCellBorder": basecolors.bg2,
        # "notebook.inactiveSelectedCellBorder": basecolors.red,
        "notebook.outputContainerBackgroundColor": basecolors.bg1,
        "notebook.outputContainerBorderColor": basecolors.bg2,
        # "notebook.selectedCellBackground": basecolors.red,
        # "notebook.selectedCellBorder": basecolors.red,
        # "notebook.symbolHighlightBackground": basecolors.red,
        # "notebookScrollbarSlider.activeBackground": basecolors.accent0,
        # "notebookScrollbarSlider.background": basecolors.red,
        # "notebookScrollbarSlider.hoverBackground": basecolors.accent0,
        # "notebookStatusErrorIcon.foreground": basecolors.red,
        # "notebookStatusRunningIcon.foreground": basecolors.red,
        # "notebookStatusSuccessIcon.foreground": basecolors.red,
        # "notebookEditorOverviewRuler.runningCellForeground": basecolors.red,

        #  <<- Chart colors ->>
        # "charts.foreground": basecolors.red,
        # "charts.lines": basecolors.red,
        # "charts.red": basecolors.red,
        # "charts.blue": basecolors.red,
        # "charts.yellow": basecolors.red,
        # "charts.orange": basecolors.red,
        # "charts.green": basecolors.red,
        # "charts.purple": basecolors.red,

        #  <<- Ports Colors ->>
        # "ports.iconRunningProcessForeground": basecolors.red,
    }
