from colors import BaseColors as bc


def get_ui_colors() -> dict:
    return {
        # https://code.visualstudio.com/api/references/theme-color
        
        # <<- Base colors ->>
        "focusBorder": bc.bg2,
        "foreground": bc.fg0,
        "disabledForeground": bc.fg1 + "90",
        "widget.border": bc.bg2,
        "widget.shadow": bc.bg0,
        # "selection.background": bc.red,
        "descriptionForeground": bc.fg1,
        "errorForeground": bc.ea0,
        "icon.foreground": bc.fg1,
        "sash.hoverBorder": bc.bg2,
        
        # <<- Window border ->>
        "window.activeBorder": bc.pa1,
        "window.inactiveBorder": bc.pa2,

        # <<- Text colors ->>
        # "textBlockQuote.background": bc.red,
        # "textBlockQuote.border": bc.red,
        # "textCodeBlock.background": bc.red,
        "textLink.activeForeground": bc.sa0,
        "textLink.foreground": bc.sa0,
        # "textPreformat.foreground": bc.red,
        # "textSeparator.foreground": bc.red,

        # <<- Action colors ->>
        "toolbar.hoverBackground": bc.bg1,
        "toolbar.hoverOutline": bc.bg0,
        "toolbar.activeBackground": bc.bg0,

        # <<- Button control ->>
        "button.background": bc.pa2,
        "button.foreground": bc.pa0,
        "button.border": bc.pa2,
        # "button.separator": bc.red,
        # "button.hoverBackground": bc.red,
        "button.secondaryForeground": bc.fg1,
        "button.secondaryBackground": bc.bg2,
        # "button.secondaryHoverBackground": bc.red,
        "checkbox.background": bc.pa2,
        "checkbox.foreground": bc.pa0,
        "checkbox.border": bc.pa2,
        # "checkbox.selectBackground": bc.red,
        # "checkbox.selectBorder": bc.red,

        # <<- Dropdown control ->>
        "dropdown.background": bc.bg1,
        "dropdown.listBackground": bc.bg1,
        "dropdown.border": bc.bg2,
        "dropdown.foreground": bc.fg0,

        # <<- Input control ->>
        "input.background": bc.bg1,
        "input.border": bc.bg2,
        "input.foreground": bc.fg0,
        "input.placeholderForeground": bc.fg1,
        "inputOption.activeBackground": bc.pa2,
        "inputOption.activeBorder": bc.pa2,
        "inputOption.activeForeground": bc.pa0,
        "inputOption.hoverBackground": bc.bg1,
        "inputValidation.errorBackground": bc.ea2,
        "inputValidation.errorForeground": bc.ea0,
        "inputValidation.errorBorder": bc.ea1,
        "inputValidation.infoBackground": bc.sa2,
        "inputValidation.infoForeground": bc.sa0,
        "inputValidation.infoBorder": bc.sa1,
        "inputValidation.warningBackground": bc.wa2,
        "inputValidation.warningForeground": bc.wa0,
        "inputValidation.warningBorder": bc.wa1,

        # <<- Scrollbar control ->>
        # "scrollbar.shadow": bc.red,
        "scrollbarSlider.activeBackground": bc.bg1 + "90",
        "scrollbarSlider.background": bc.bg2 + "90",
        "scrollbarSlider.hoverBackground": bc.bg1 + "90",

        # <<- Badge ->>
        "badge.foreground": bc.pa0,
        "badge.background": bc.pa2,

        # <<- Progress bar ->>
        "progressBar.background": bc.pa0,

        # <<- Lists and trees ->>
        "list.activeSelectionBackground": bc.bg2,
        "list.activeSelectionForeground": bc.fg0,
        "list.activeSelectionIconForeground": bc.fg0,
        "list.dropBackground": bc.bg1,
        "list.focusBackground": bc.bg0,
        "list.focusForeground": bc.fg0,
        # "list.focusHighlightForeground": bc.red,
        # "list.focusOutline": bc.red,
        # "list.focusAndSelectionOutline": bc.red,
        # "list.highlightForeground": bc.red,
        "list.hoverBackground": bc.bg0,
        "list.hoverForeground": bc.fg0,
        "list.inactiveSelectionBackground": bc.bg1,
        # "list.inactiveSelectionForeground": bc.red,
        # "list.inactiveSelectionIconForeground": bc.red,
        # "list.inactiveFocusBackground": bc.red,
        # "list.inactiveFocusOutline": bc.red,
        # "list.invalidItemForeground": bc.red,
        "list.errorForeground": bc.ea0,
        "list.warningForeground": bc.wa0,
        # "listFilterWidget.background": bc.red,
        # "listFilterWidget.outline": bc.red,
        # "listFilterWidget.noMatchesOutline": bc.red,
        # "listFilterWidget.shadow": bc.red,
        # "list.filterMatchBackground": bc.red,
        # "list.filterMatchBorder": bc.red,
        # "list.deemphasizedForeground": bc.red,
        "tree.indentGuidesStroke": bc.bg1,
        "tree.inactiveIndentGuidesStroke": bc.bg1,
        "tree.tableColumnsBorder": bc.bg2,
        "tree.tableOddRowsBackground": bc.bg1,

        # <<- Activity Bar ->>
        "activityBar.background": bc.bg0,
        "activityBar.dropBorder": bc.bg2,
        "activityBar.foreground": bc.fg0,
        "activityBar.inactiveForeground": bc.fg2,
        "activityBar.border": bc.bg2,
        "activityBarBadge.background": bc.pa2,
        "activityBarBadge.foreground": bc.pa0,
        "activityBar.activeBorder": bc.pa0,
        "activityBar.activeBackground": bc.bg0,
        "activityBar.activeFocusBorder": bc.pa0,

        # <<- Side Bar ->>
        "sideBar.background": bc.bg0,
        "sideBar.foreground": bc.fg1,
        "sideBar.border": bc.bg2,
        "sideBar.dropBackground": bc.bg1,
        "sideBarTitle.foreground": bc.fg0,
        "sideBarSectionHeader.background": bc.bg0,
        "sideBarSectionHeader.foreground": bc.fg0,
        "sideBarSectionHeader.border": bc.bg2,

        # <<- Minimap ->>
        # "minimap.findMatchHighlight": bc.red,
        "minimap.selectionHighlight": bc.sa0,
        "minimap.errorHighlight": bc.ea0,
        "minimap.warningHighlight": bc.wa0,
        # "minimap.background": bc.red,
        # "minimap.selectionOccurrenceHighlight": bc.red,
        # "minimap.foregroundOpacity": bc.red,
        # "minimapSlider.background": bc.red,
        # "minimapSlider.hoverBackground": bc.red,
        # "minimapSlider.activeBackground": bc.red,
        "minimapGutter.addedBackground": bc.pa1,
        "minimapGutter.modifiedBackground": bc.sa1,
        "minimapGutter.deletedBackground": bc.ea1,

        # <<- Editor Groups & Tabs ->>
        "editorGroup.border": bc.bg2,
        "editorGroup.dropBackground": bc.bg1,
        "editorGroupHeader.noTabsBackground": bc.bg0,
        "editorGroupHeader.tabsBackground": bc.bg0,
        "editorGroupHeader.tabsBorder": bc.bg2,
        "editorGroupHeader.border": bc.bg2,
        "editorGroup.emptyBackground": bc.bg1,
        # "editorGroup.focusedEmptyBorder": bc.red,
        # "editorGroup.dropIntoPromptForeground": bc.red,
        # "editorGroup.dropIntoPromptBackground": bc.red,
        # "editorGroup.dropIntoPromptBorder": bc.red,
        "tab.activeBackground": bc.bg0,
        "tab.unfocusedActiveBackground": bc.bg0,
        "tab.activeForeground": bc.fg0,
        "tab.unfocusedActiveForeground": bc.fg0,
        "tab.border": bc.bg2,
        "tab.activeBorder": bc.bg0,
        "tab.unfocusedActiveBorder": bc.bg0,
        "tab.activeBorderTop": bc.pa0,
        "tab.unfocusedActiveBorderTop": bc.pa0,
        "tab.lastPinnedBorder": bc.bg2,
        "tab.inactiveBackground": bc.bg0,
        "tab.unfocusedInactiveBackground": bc.bg0,
        "tab.inactiveForeground": bc.fg1,
        "tab.unfocusedInactiveForeground": bc.fg1,
        "tab.hoverBackground": bc.bg0,
        "tab.unfocusedHoverBackground": bc.bg0,
        "tab.hoverForeground": bc.fg0,
        "tab.unfocusedHoverForeground": bc.fg1,
        # "tab.hoverBorder": bc.red,
        # "tab.unfocusedHoverBorder": bc.red,
        # "tab.activeModifiedBorder": bc.red,
        # "tab.inactiveModifiedBorder": bc.red,
        # "tab.unfocusedActiveModifiedBorder": bc.red,
        # "tab.unfocusedInactiveModifiedBorder": bc.red,
        # "editorPane.background": bc.red,
        # "sideBySideEditor.horizontalBorder": bc.red,
        # "sideBySideEditor.verticalBorder": bc.red,

        # <<- Editor colors ->>
        "editor.background": bc.bg0,
        "editor.foreground": bc.fg0,
        "editorLineNumber.foreground": bc.fg2,
        "editorLineNumber.activeForeground": bc.fg1,
        # "editorLineNumber.dimmedForeground": bc.red,
        "editorCursor.background": bc.pa0,
        "editorCursor.foreground": bc.pa0,
        "editor.selectionBackground": bc.sa0 + "30",
        # "editor.selectionForeground": bc.red,
        "editor.inactiveSelectionBackground": bc.sa0 + "50",
        "editor.selectionHighlightBackground": bc.sa0 + "30",
        # "editor.selectionHighlightBorder": bc.red,
        # "editor.wordHighlightBackground": bc.red,
        # "editor.wordHighlightBorder": bc.red,
        # "editor.wordHighlightStrongBackground": bc.red,
        # "editor.wordHighlightStrongBorder": bc.red,
        # "editor.wordHighlightTextBackground": bc.red,
        # "editor.wordHighlightTextBorder": bc.red,
        # "editor.findMatchBackground": bc.red,
        # "editor.findMatchHighlightBackground": bc.red,
        # "editor.findRangeHighlightBackground": bc.red,
        # "editor.findMatchBorder": bc.red,
        # "editor.findMatchHighlightBorder": bc.red,
        # "editor.findRangeHighlightBorder": bc.red,
        # "searchEditor.findMatchBackground": bc.red,
        # "searchEditor.findMatchBorder": bc.red,
        # "searchEditor.textInputBorder": bc.red,
        "editor.hoverHighlightBackground": bc.sa0 + "30",
        "editor.lineHighlightBackground": bc.bg0,
        "editor.lineHighlightBorder": bc.bg0,
        # "editorUnicodeHighlight.border": bc.red,
        # "editorUnicodeHighlight.background": bc.red,
        # "editorLink.activeForeground": bc.red,
        # "editor.rangeHighlightBackground": bc.red,
        # "editor.rangeHighlightBorder": bc.red,
        # "editor.symbolHighlightBackground": bc.red,
        # "editor.symbolHighlightBorder": bc.red,
        "editorWhitespace.foreground": bc.bg2,
        "editorIndentGuide.background": bc.bg1,
        "editorIndentGuide.activeBackground": bc.bg1,
        # "editorInlayHint.background": bc.bg1,
        # "editorInlayHint.foreground": bc.bg1,
        # "editorInlayHint.typeForeground": bc.bg1,
        # "editorInlayHint.typeBackground": bc.bg1,
        # "editorInlayHint.parameterForeground": bc.bg1,
        # "editorInlayHint.parameterBackground": bc.bg1,
        "editorRuler.foreground": bc.bg1,
        # "editor.linkedEditingBackground": bc.bg1,
        # "editorCodeLens.foreground": bc.red,
        "editorLightBulb.foreground": bc.wa0,
        "editorLightBulbAutoFix.foreground": bc.pa0,
        # "editorBracketMatch.foreground": bc.red,
        # "editorBracketMatch.border": bc.red,
        # <<- Handled in theming_extras.py ->> <| START |>
        # "editorBracketHighlight.foreground1": bc.fg0 + "90",
        # "editorBracketHighlight.foreground2": bc.fg0 + "90",
        # "editorBracketHighlight.foreground3": bc.fg0 + "90",
        # "editorBracketHighlight.foreground4": bc.fg0 + "90",
        # "editorBracketHighlight.foreground5": bc.fg0 + "90",
        # "editorBracketHighlight.foreground6": bc.fg0 + "90",
        # "editorBracketHighlight.unexpectedBracket.foreground": bc.red,
        # "editorBracketPairGuide.activeBackground1": bc.red,
        # "editorBracketPairGuide.activeBackground2": bc.red,
        # "editorBracketPairGuide.activeBackground3": bc.red,
        # "editorBracketPairGuide.activeBackground4": bc.red,
        # "editorBracketPairGuide.activeBackground5": bc.red,
        # "editorBracketPairGuide.activeBackground6": bc.red,
        # "editorBracketPairGuide.background1": bc.red,
        # "editorBracketPairGuide.background2": bc.red,
        # "editorBracketPairGuide.background3": bc.red,
        # "editorBracketPairGuide.background4": bc.red,
        # "editorBracketPairGuide.background5": bc.red,
        # "editorBracketPairGuide.background6": bc.red,
        # <<- Handled in theming_extras.py ->> <| END |>
        # "editor.foldBackground": bc.red,
        # "editorOverviewRuler.background": bc.red,
        # "editorOverviewRuler.border": bc.red,
        # "editorOverviewRuler.findMatchForeground": bc.red,
        # "editorOverviewRuler.rangeHighlightForeground": bc.red,
        # "editorOverviewRuler.selectionHighlightForeground": bc.red,
        # "editorOverviewRuler.wordHighlightForeground": bc.red,
        # "editorOverviewRuler.wordHighlightStrongForeground": bc.red,
        # "editorOverviewRuler.wordHighlightTextForeground": bc.red,
        # "editorOverviewRuler.modifiedForeground": bc.red,
        # "editorOverviewRuler.addedForeground": bc.red,
        # "editorOverviewRuler.deletedForeground": bc.red,
        # "editorOverviewRuler.errorForeground": bc.red,
        # "editorOverviewRuler.warningForeground": bc.red,
        # "editorOverviewRuler.infoForeground": bc.red,
        # "editorOverviewRuler.bracketMatchForeground": bc.red,
        "editorError.foreground": bc.ea0,
        # "editorError.border": bc.red,
        # "editorError.background": bc.red,
        # "editorWarning.foreground": bc.red,
        # "editorWarning.border": bc.red,
        # "editorWarning.background": bc.red,
        # "editorInfo.foreground": bc.red,
        # "editorInfo.border": bc.red,
        # "editorInfo.background": bc.red,
        # "editorHint.foreground": bc.red,
        # "editorHint.border": bc.red,
        "problemsErrorIcon.foreground": bc.ea0,
        "problemsWarningIcon.foreground": bc.wa0,
        "problemsInfoIcon.foreground": bc.sa0,
        # "editorUnnecessaryCode.border": bc.red,
        # "editorUnnecessaryCode.opacity": bc.red,
        # "editorUnnecessaryCode.opacity": bc.red,
        "editorGutter.modifiedBackground": bc.sa1,
        "editorGutter.addedBackground": bc.pa1,
        "editorGutter.deletedBackground": bc.ea1,
        # "editorGutter.commentRangeForeground": bc.red,
        # "editorGutter.commentGlyphForground": bc.red,
        # "editorGutter.foldingControlForeground": bc.red,
        # "editorCommentsWidget.resolvedBorder": bc.red,
        # "editorCommentsWidget.unresolvedBorder": bc.red,
        # "editorCommentsWidget.rangeBackground": bc.red,
        # "editorCommentsWidget.rangeBorder": bc.red,
        # "editorCommentsWidget.rangeActiveBackground": bc.red,
        # "editorCommentsWidget.rangeActiveBorder": bc.red,

        # <<- Diff editor colors ->>
        "diffEditor.insertedTextBackground": bc.pa2 + "90",
        # "diffEditor.insertedTextBorder": bc.red,
        "diffEditor.removedTextBackground": bc.ea2 + "90",
        # "diffEditor.removedTextBorder": bc.red,
        "diffEditor.border": bc.bg2,
        "diffEditor.diagonalFill": bc.sa0 + "20",
        "diffEditor.insertedLineBackground": bc.pa2 + "70",
        "diffEditor.removedLineBackground": bc.ea2 + "70",
        "diffEditorGutter.insertedLineBackground": bc.pa2 + "90",
        "diffEditorGutter.removedLineBackground": bc.ea2 + "90",
        "diffEditorOverview.insertedForeground": bc.pa2,
        "diffEditorOverview.removedForeground": bc.ea2,

        # <<- Editor widget colors ->>
        "editorWidget.foreground": bc.fg0,
        "editorWidget.background": bc.bg0,
        "editorWidget.border": bc.pa0,
        "editorWidget.resizeBorder": bc.pa0,
        "editorSuggestWidget.background": bc.bg1,
        "editorSuggestWidget.border": bc.bg2,
        "editorSuggestWidget.foreground": bc.fg1,
        # "editorSuggestWidget.focusHighlightForeground": bc.red,
        # "editorSuggestWidget.highlightForeground": bc.red,
        "editorSuggestWidget.selectedBackground": bc.bg0,
        "editorSuggestWidget.selectedForeground": bc.fg0,
        "editorSuggestWidget.selectedIconForeground": bc.pa0,
        # "editorSuggestWidgetStatus.foreground": bc.red,
        "editorHoverWidget.foreground": bc.fg0,
        "editorHoverWidget.background": bc.bg1,
        "editorHoverWidget.border": bc.bg2,
        # "editorHoverWidget.highlightForeground": bc.red,
        # "editorHoverWidget.statusBarBackground": bc.red,
        # "editorGhostText.border": bc.red,
        # "editorGhostText.background": bc.red,
        # "editorGhostText.foreground": bc.red,
        "editorStickyScroll.background": bc.bg0,
        "editorStickyScrollHover.background": bc.bg1,
        # "debugExceptionWidget.background": bc.red,
        # "debugExceptionWidget.border": bc.red,
        # "editorMarkerNavigation.background": bc.red,
        # "editorMarkerNavigationError.background": bc.red,
        # "editorMarkerNavigationWarning.background": bc.red,
        # "editorMarkerNavigationInfo.background": bc.red,
        # "editorMarkerNavigationError.headerBackground": bc.red,
        # "editorMarkerNavigationWarning.headerBackground": bc.red,
        # "editorMarkerNavigationInfo.headerBackground": bc.red,

        # <<- Peek view colors ->>
        "peekView.border": bc.bg2,
        "peekViewEditor.background": bc.bg0,
        "peekViewEditorGutter.background": bc.bg0,
        # "peekViewEditor.matchHighlightBackground": bc.red,
        # "peekViewEditor.matchHighlightBorder": bc.red,
        "peekViewEditorStickScroll.background": bc.bg0,
        "peekViewResult.background": bc.bg1,
        "peekViewResult.fileForeground": bc.fg0,
        "peekViewResult.lineForeground": bc.fg0,
        # "peekViewResult.matchHighlightBackground": bc.red,
        "peekViewResult.selectionBackground": bc.bg0,
        "peekViewResult.selectionForeground": bc.fg0,
        "peekViewTitle.background": bc.bg1,
        "peekViewTitleDescription.foreground": bc.fg1,
        "peekViewTitleLabel.foreground": bc.fg0,

        # <<- Merge conflicts colors ->>
        "merge.currentHeaderBackground": bc.pa1 + "90",
        "merge.currentContentBackground": bc.pa2 + "90",
        "merge.incomingHeaderBackground": bc.sa1 + "90",
        "merge.incomingContentBackground": bc.sa2 + "90",
        # "merge.border": bc.red,
        # "merge.commonContentBackground": bc.red,
        # "merge.commonHeaderBackground": bc.red,
        # "editorOverviewRuler.currentContentForeground": bc.red,
        # "editorOverviewRuler.incomingContentForeground": bc.red,
        # "editorOverviewRuler.commonContentForeground": bc.red,
        "mergeEditor.change.background": bc.pa2 + "90",
        "mergeEditor.change.word.background": bc.pa1 + "90",
        "mergeEditor.conflict.unhandledUnfocused.border": bc.wa1,
        "mergeEditor.conflict.unhandledFocused.border": bc.wa1,
        "mergeEditor.conflict.handledUnfocused.border": bc.pa1,
        "mergeEditor.conflict.handledFocused.border": bc.pa1,
        "mergeEditor.conflict.handled.minimapOverViewRuler": bc.pa1,
        "mergeEditor.conflict.unhandled.minimapOverViewRuler": bc.wa1,
        # "mergeEditor.conflictingLines.background": bc.red,
        # "mergeEditor.changeBase.background": bc.red,
        # "mergeEditor.changeBase.word.background": bc.red,
        # "mergeEditor.conflict.input1.background": bc.red,
        # "mergeEditor.conflict.input2.background": bc.red,

        # <<- Panel colors ->>
        "panel.background": bc.bg0,
        "panel.border": bc.bg2,
        "panel.dropBorder": bc.bg2,
        "panelTitle.activeBorder": bc.pa0,
        "panelTitle.activeForeground": bc.fg0,
        "panelTitle.inactiveForeground": bc.fg1,
        "panelInput.border": bc.bg2,
        # "panelSection.border": bc.red,
        "panelSection.dropBackground": bc.bg1,
        # "panelSectionHeader.background": bc.red,
        # "panelSectionHeader.foreground": bc.red,
        # "panelSectionHeader.border": bc.red,

        # <<- Status Bar colors ->>
        "statusBar.background": bc.bg0,
        "statusBar.foreground": bc.fg1,
        "statusBar.border": bc.bg2,
        "statusBar.debuggingBackground": bc.da2,
        "statusBar.debuggingForeground": bc.da0,
        "statusBar.debuggingBorder": bc.bg2,
        "statusBar.noFolderForeground": bc.sa0,
        "statusBar.noFolderBackground": bc.sa2,
        "statusBar.noFolderBorder": bc.bg2,
        # "statusBarItem.activeBackground": bc.bg0,
        # "statusBarItem.hoverBackground": bc.bg0,
        # "statusBarItem.prominentForeground": bc.bg0,
        # "statusBarItem.prominentBackground": bc.bg0,
        # "statusBarItem.prominentHoverBackground": bc.bg0,
        "statusBarItem.remoteBackground": bc.pa2,
        "statusBarItem.remoteForeground": bc.pa0,
        "statusBarItem.errorBackground": bc.ea2,
        "statusBarItem.errorForeground": bc.ea0,
        "statusBarItem.warningBackground": bc.wa2,
        "statusBarItem.warningForeground": bc.wa0,
        # "statusBarItem.compactHoverBackground": bc.bg0,
        # "statusBarItem.focusBorder": bc.bg0,
        # "statusBar.focusBorder": bc.bg0,

        # <<- Title Bar colors ->>
        "titleBar.activeBackground": bc.bg0,
        "titleBar.activeForeground": bc.fg1,
        "titleBar.inactiveBackground": bc.bg0,
        "titleBar.inactiveForeground": bc.fg1,
        "titleBar.border": bc.bg2,

        # <<- Menu Bar colors ->>
        "menubar.selectionForeground": bc.fg0,
        "menubar.selectionBackground": bc.bg0,
        "menubar.selectionBorder": bc.bg0,
        "menu.foreground": bc.fg1,
        "menu.background": bc.bg1,
        "menu.selectionForeground": bc.fg0,
        "menu.selectionBackground": bc.bg0,
        "menu.selectionBorder": bc.bg0,
        "menu.separatorBackground": bc.bg2,
        "menu.border": bc.bg2,

        # <<- Command Center colors ->>
        "commandCenter.foreground": bc.fg1,
        "commandCenter.background": bc.bg1,
        "commandCenter.border": bc.bg2,
        "commandCenter.activeForeground": bc.fg0,
        "commandCenter.activeBackground": bc.bg0,
        "commandCenter.activeBorder": bc.bg2,
        "commandCenter.inactiveBorder": bc.bg2,
        "commandCenter.inactiveForeground": bc.fg1,

        # <<- Notification colors ->>
        "notificationCenter.border": bc.bg2,
        "notificationCenterHeader.foreground": bc.fg1,
        "notificationCenterHeader.background": bc.bg1,
        "notificationToast.border": bc.bg2,
        "notifications.foreground": bc.fg1,
        "notifications.background": bc.bg1,
        "notifications.border": bc.bg2,
        "notificationLink.foreground": bc.sa0,
        "notificationsErrorIcon.foreground": bc.ea0,
        "notificationsWarningIcon.foreground": bc.wa0,
        "notificationsInfoIcon.foreground": bc.sa0,

        # <<- Banner colors ->>
        # "banner.background": bc.red,
        # "banner.foreground": bc.red,
        # "banner.iconForeground": bc.red,

        # <<- Extensions colors ->>
        "extensionButton.prominentForeground": bc.pa0,
        "extensionButton.prominentBackground": bc.pa2,
        # "extensionButton.prominentHoverBackground": bc.pa0,
        "extensionButton.background": bc.pa2,
        "extensionButton.foreground": bc.pa0,
        "extensionButton.hoverBackground": bc.pa2,
        "extensionButton.separator": bc.pa2,
        "extensionBadge.remoteBackground": bc.pa2,
        "extensionBadge.remoteForeground": bc.pa0,
        "extensionIcon.starForeground": bc.pa0,
        "extensionIcon.verifiedForeground": bc.pa0,
        # "extensionIcon.preReleaseForeground": bc.red,
        # "extensionIcon.sponsorForeground": bc.red,

        # <<- Quick picker colors ->>
        "pickerGroup.border": bc.bg2,
        # "pickerGroup.foreground": bc.fg0,
        "quickInput.background": bc.bg1,
        "quickInput.foreground": bc.fg1,
        "quickInputList.focusBackground": bc.bg0,
        "quickInputList.focusForeground": bc.fg0,
        "quickInputList.focusIconForeground": bc.fg0,
        # "quickInputTitle.background": bc.red,

        # <<- Keybinding label colors ->>
        "keybindingLabel.background": bc.pa2,
        "keybindingLabel.foreground": bc.pa0,
        "keybindingLabel.border": bc.pa2,
        "keybindingLabel.bottomBorder": bc.pa2,

        # <<- Keyboard shortcut table colors ->>
        "keybindingTable.headerBackground": bc.bg0,
        "keybindingTable.rowsBackground": bc.bg0,

        # <<- Integrated Terminal colors ->>
        "terminal.background": bc.bg0,
        "terminal.border": bc.bg2,
        "terminal.foreground": bc.fg0,
        "terminal.ansiBlack": bc.ansiBlack,
        "terminal.ansiBlue": bc.ansiBrightBlack,
        "terminal.ansiBrightBlack": bc.ansiBrightBlack,
        "terminal.ansiBrightBlue": bc.ansiBrightBlue,
        "terminal.ansiBrightCyan": bc.ansiBrightCyan,
        "terminal.ansiBrightGreen": bc.ansiBrightGreen,
        "terminal.ansiBrightMagenta": bc.ansiBrightMagenta,
        "terminal.ansiBrightRed": bc.ansiBrightRed,
        "terminal.ansiBrightWhite": bc.ansiBrightWhite,
        "terminal.ansiBrightYellow": bc.ansiBrightYellow,
        "terminal.ansiCyan": bc.ansiCyan,
        "terminal.ansiGreen": bc.ansiGreen,
        "terminal.ansiMagenta": bc.ansiMagenta,
        "terminal.ansiRed": bc.ansiRed,
        "terminal.ansiWhite": bc.ansiWhite,
        "terminal.ansiYellow": bc.ansiYellow,
        # "terminal.selectionBackground": bc.red,
        # "terminal.selectionForeground": bc.red,
        # "terminal.inactiveSelectionBackground": bc.red,
        # "terminal.findMatchBackground": bc.red,
        # "terminal.findMatchBorder": bc.red,
        # "terminal.findMatchHighlightBackground": bc.red,
        # "terminal.findMatchHighlightBorder": bc.red,
        "terminalCursor.background": bc.pa0,
        "terminalCursor.foreground": bc.pa0,
        "terminal.dropBackground": bc.bg1,
        "terminal.tab.activeBorder": bc.pa0,
        # "terminalCommandDecoration.defaultBackground": bc.red,
        # "terminalCommandDecoration.successBackground": bc.red,
        # "terminalCommandDecoration.errorBackground": bc.red,
        # "terminalOverviewRuler.cursorForeground": bc.red,
        # "terminalOverviewRuler.findMatchForeground": bc.red,

        # <<- Debug colors ->>
        "debugToolBar.background": bc.bg0,
        "debugToolBar.border": bc.bg2,
        # "editor.stackFrameHighlightBackground": bc.red,
        # "editor.focusedStackFrameHighlightBackground": bc.red,
        # "editor.inlineValuesForeground": bc.red,
        # "editor.inlineValuesBackground": bc.red,
        # "debugView.exceptionLabelForeground": bc.red,
        # "debugView.exceptionLabelBackground": bc.red,
        # "debugView.stateLabelForeground": bc.red,
        # "debugView.stateLabelBackground": bc.red,
        # "debugView.valueChangedHighlight": bc.red,
        # "debugTokenExpression.name": bc.red,
        # "debugTokenExpression.value": bc.red,
        # "debugTokenExpression.string": bc.red,
        # "debugTokenExpression.boolean": bc.red,
        # "debugTokenExpression.number": bc.red,
        # "debugTokenExpression.error": bc.red,

        # <<- Testing colors ->>
        # "testing.iconFailed": bc.red,
        # "testing.iconErrored": bc.red,
        # "testing.iconPassed": bc.red,
        # "testing.runAction": bc.red,
        # "testing.iconQueued": bc.red,
        # "testing.iconUnset": bc.red,
        # "testing.iconSkipped": bc.red,
        # "testing.peekBorder": bc.red,
        # "testing.peekHeaderBackground": bc.red,
        # "testing.message.error.decorationForeground": bc.red,
        # "testing.message.error.lineBackground": bc.red,
        # "testing.message.info.decorationForeground": bc.red,
        # "testing.message.info.lineBackground": bc.red,

        # <<- Welcome page colors ->>
        "welcomePage.background": bc.bg0,
        "welcomePage.progress.background": bc.bg2,
        "welcomePage.progress.foreground": bc.pa2,
        "welcomePage.tileBackground": bc.bg1,
        "welcomePage.tileHoverBackground": bc.bg2,
        "welcomePage.tileBorder": bc.bg0,
        # "walkThrough.embeddedEditorBackground": bc.red,
        # "walkthrough.stepTitle.foreground": bc.red,
        # "welcomeOverlay.background": bc.red,

        # <<- Source Control colors ->>
        # "scm.providerBorder": bc.red,

        # <<- Git colors ->>
        "gitDecoration.addedResourceForeground": bc.pa0,
        "gitDecoration.modifiedResourceForeground": bc.sa0,
        "gitDecoration.deletedResourceForeground": bc.ea0,
        "gitDecoration.renamedResourceForeground": bc.wa0,
        # "gitDecoration.stageModifiedResourceForeground": bc.red,
        # "gitDecoration.stageDeletedResourceForeground": bc.red,
        # "gitDecoration.untrackedResourceForeground": bc.red,
        # "gitDecoration.ignoredResourceForeground": bc.red,
        # "gitDecoration.conflictingResourceForeground": bc.red,
        # "gitDecoration.submoduleResourceForeground": bc.red,

        # <<- Settings Editor colors ->>
        # "settings.headerForeground": bc.pa0,
        "settings.modifiedItemIndicator": bc.pa0,
        "settings.dropdownBackground": bc.bg1,
        "settings.dropdownForeground": bc.fg1,
        "settings.dropdownBorder": bc.bg2,
        "settings.dropdownListBorder": bc.bg2,
        "settings.checkboxBackground": bc.pa2,
        "settings.checkboxForeground": bc.pa0,
        "settings.checkboxBorder": bc.pa2,
        "settings.rowHoverBackground": bc.bg1,
        "settings.textInputBackground": bc.bg1,
        "settings.textInputForeground": bc.fg1,
        "settings.textInputBorder": bc.bg2,
        "settings.numberInputBackground": bc.bg1,
        "settings.numberInputForeground": bc.fg1,
        "settings.numberInputBorder": bc.bg2,
        "settings.focusedRowBackground": bc.bg1,
        "settings.focusedRowBorder": bc.bg2,
        "settings.headerBorder": bc.bg2,
        "settings.sashBorder": bc.bg2,
        # "settings.settingsHeaderHoverForeground": bc.red,

        # <<- Breadcrumbs colors ->>
        "breadcrumb.foreground": bc.fg1,
        "breadcrumb.background": bc.bg0,
        "breadcrumb.focusForeground": bc.fg0,
        "breadcrumb.activeSelectionForeground": bc.fg0,
        "breadcrumbPicker.background": bc.bg1,

        # <<- Snippets colors ->>
        # "editor.snippetTabstopHighlightBackground": bc.red,
        # "editor.snippetTabstopHighlightBorder": bc.red,
        # "editor.snippetFinalTabstopHighlightBackground": bc.red,
        # "editor.snippetFinalTabstopHighlightBorder": bc.red,

        # <<- Symbol Icon colors ->>
        # <<- Handled in theming_extras.py ->> <| START |>
        # "symbolIcon.arrayForeground": bc.fg0,
        # "symbolIcon.booleanForeground": bc.fg0,
        # "symbolIcon.classForeground": bc.fg0,
        # "symbolIcon.colorForeground": bc.fg0,
        # "symbolIcon.constantForeground": bc.fg0,
        # "symbolIcon.constructorForeground": bc.fg0,
        # "symbolIcon.enumeratorForeground": bc.fg0,
        # "symbolIcon.enumeratorMemberForeground": bc.fg0,
        # "symbolIcon.eventForeground": bc.fg0,
        # "symbolIcon.fieldForeground": bc.fg0,
        # "symbolIcon.fileForeground": bc.fg0,
        # "symbolIcon.folderForeground": bc.fg0,
        # "symbolIcon.functionForeground": bc.fg0,
        # "symbolIcon.interfaceForeground": bc.fg0,
        # "symbolIcon.keyForeground": bc.fg0,
        # "symbolIcon.keywordForeground": bc.fg0,
        # "symbolIcon.methodForeground": bc.fg0,
        # "symbolIcon.moduleForeground": bc.fg0,
        # "symbolIcon.namespaceForeground": bc.fg0,
        # "symbolIcon.nullForeground": bc.fg0,
        # "symbolIcon.numberForeground": bc.fg0,
        # "symbolIcon.objectForeground": bc.fg0,
        # "symbolIcon.operatorForeground": bc.fg0,
        # "symbolIcon.packageForeground": bc.fg0,
        # "symbolIcon.propertyForeground": bc.fg0,
        # "symbolIcon.referenceForeground": bc.fg0,
        # "symbolIcon.snippetForeground": bc.fg0,
        # "symbolIcon.stringForeground": bc.fg0,
        # "symbolIcon.structForeground": bc.fg0,
        # "symbolIcon.textForeground": bc.fg0,
        # "symbolIcon.typeParameterForeground": bc.fg0,
        # "symbolIcon.unitForeground": bc.fg0,
        # "symbolIcon.variableForeground": bc.fg0,
        # <<- Handled in theming_extras.py ->> <| END |>

        # <<- Debug Icons colors ->>
        "debugIcon.breakpointForeground": bc.ea0,
        # "debugIcon.breakpointDisabledForeground": bc.red,
        # "debugIcon.breakpointUnverifiedForeground": bc.red,
        # "debugIcon.breakpointCurrentStackframeForeground": bc.red,
        # "debugIcon.breakpointStackframeForeground": bc.red,
        "debugIcon.startForeground": bc.sa0,
        "debugIcon.pauseForeground": bc.sa0,
        "debugIcon.stopForeground": bc.ea0,
        "debugIcon.disconnectForeground": bc.pa0,
        "debugIcon.restartForeground": bc.pa0,
        "debugIcon.stepOverForeground": bc.sa0,
        "debugIcon.stepIntoForeground": bc.sa0,
        "debugIcon.stepOutForeground": bc.sa0,
        "debugIcon.continueForeground": bc.sa0,
        "debugIcon.stepBackForeground": bc.sa0,
        "debugConsole.infoForeground": bc.ansiBrightBlue,
        "debugConsole.warningForeground": bc.ansiBrightYellow,
        "debugConsole.errorForeground": bc.ansiBrightRed,
        "debugConsole.sourceForeground": bc.fg0,
        "debugConsoleInputIcon.foreground": bc.sa0,

        # <<- Notebook colors ->>
        "notebook.editorBackground": bc.bg0,
        "notebook.cellBorderColor": bc.bg2,
        "notebook.cellHoverBackground": bc.bg0,
        # "notebook.cellInsertionIndicator": bc.red,
        # "notebook.cellStatusBarItemHoverBackground": bc.red,
        # "notebook.cellToolbarSeparator": bc.red,
        # "notebook.cellEditorBackground": bc.red,
        "notebook.focusedCellBackground": bc.bg0,
        "notebook.focusedCellBorder": bc.pa1,
        "notebook.focusedEditorBorder": bc.bg2,
        "notebook.inactiveFocusedCellBorder": bc.bg2,
        # "notebook.inactiveSelectedCellBorder": bc.red,
        "notebook.outputContainerBackgroundColor": bc.bg1,
        "notebook.outputContainerBorderColor": bc.bg2,
        # "notebook.selectedCellBackground": bc.red,
        # "notebook.selectedCellBorder": bc.red,
        # "notebook.symbolHighlightBackground": bc.red,
        "notebookScrollbarSlider.activeBackground": bc.bg1 + "90",
        "notebookScrollbarSlider.background": bc.bg2 + "90",
        "notebookScrollbarSlider.hoverBackground": bc.bg1 + "90",
        # "notebookStatusErrorIcon.foreground": bc.red,
        # "notebookStatusRunningIcon.foreground": bc.red,
        # "notebookStatusSuccessIcon.foreground": bc.red,
        # "notebookEditorOverviewRuler.runningCellForeground": bc.red,

        # <<- Chart colors ->>
        # "charts.foreground": bc.red,
        # "charts.lines": bc.red,
        # "charts.red": bc.red,
        # "charts.blue": bc.red,
        # "charts.yellow": bc.red,
        # "charts.orange": bc.red,
        # "charts.green": bc.red,
        # "charts.purple": bc.red,

        # <<- Ports Colors ->>
        # "ports.iconRunningProcessForeground": bc.red,
    }
